// <auto-generated />
using System;
using Haczykowefajtlapy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Haczykowefajtlapy.Migrations
{
    [DbContext(typeof(FishingClubContext))]
    [Migration("20250530171302_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Haczykowefajtlapy.Model.CompetitionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<string>("FishType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<int>("Place")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("MemberId");

                    b.ToTable("CompetitionResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompetitionId = 1,
                            FishType = "Pike",
                            MemberId = 1,
                            Place = 1,
                            Weight = 1.5m
                        },
                        new
                        {
                            Id = 2,
                            CompetitionId = 1,
                            FishType = "Carp",
                            MemberId = 2,
                            Place = 2,
                            Weight = 2.0m
                        },
                        new
                        {
                            Id = 3,
                            CompetitionId = 1,
                            FishType = "Pike",
                            MemberId = 3,
                            Place = 3,
                            Weight = 2.5m
                        },
                        new
                        {
                            Id = 4,
                            CompetitionId = 1,
                            FishType = "Carp",
                            MemberId = 4,
                            Place = 4,
                            Weight = 3.0m
                        },
                        new
                        {
                            Id = 5,
                            CompetitionId = 1,
                            FishType = "Pike",
                            MemberId = 5,
                            Place = 5,
                            Weight = 3.5m
                        },
                        new
                        {
                            Id = 6,
                            CompetitionId = 1,
                            FishType = "Carp",
                            MemberId = 6,
                            Place = 6,
                            Weight = 4.0m
                        },
                        new
                        {
                            Id = 7,
                            CompetitionId = 1,
                            FishType = "Pike",
                            MemberId = 7,
                            Place = 7,
                            Weight = 4.5m
                        },
                        new
                        {
                            Id = 8,
                            CompetitionId = 1,
                            FishType = "Carp",
                            MemberId = 8,
                            Place = 8,
                            Weight = 5.0m
                        },
                        new
                        {
                            Id = 9,
                            CompetitionId = 1,
                            FishType = "Pike",
                            MemberId = 9,
                            Place = 9,
                            Weight = 5.5m
                        },
                        new
                        {
                            Id = 10,
                            CompetitionId = 1,
                            FishType = "Carp",
                            MemberId = 10,
                            Place = 10,
                            Weight = 6.0m
                        },
                        new
                        {
                            Id = 11,
                            CompetitionId = 2,
                            FishType = "Pike",
                            MemberId = 1,
                            Place = 1,
                            Weight = 1.5m
                        },
                        new
                        {
                            Id = 12,
                            CompetitionId = 2,
                            FishType = "Carp",
                            MemberId = 2,
                            Place = 2,
                            Weight = 2.0m
                        },
                        new
                        {
                            Id = 13,
                            CompetitionId = 2,
                            FishType = "Pike",
                            MemberId = 3,
                            Place = 3,
                            Weight = 2.5m
                        },
                        new
                        {
                            Id = 14,
                            CompetitionId = 2,
                            FishType = "Carp",
                            MemberId = 4,
                            Place = 4,
                            Weight = 3.0m
                        },
                        new
                        {
                            Id = 15,
                            CompetitionId = 2,
                            FishType = "Pike",
                            MemberId = 5,
                            Place = 5,
                            Weight = 3.5m
                        },
                        new
                        {
                            Id = 16,
                            CompetitionId = 2,
                            FishType = "Carp",
                            MemberId = 6,
                            Place = 6,
                            Weight = 4.0m
                        },
                        new
                        {
                            Id = 17,
                            CompetitionId = 2,
                            FishType = "Pike",
                            MemberId = 7,
                            Place = 7,
                            Weight = 4.5m
                        },
                        new
                        {
                            Id = 18,
                            CompetitionId = 2,
                            FishType = "Carp",
                            MemberId = 8,
                            Place = 8,
                            Weight = 5.0m
                        },
                        new
                        {
                            Id = 19,
                            CompetitionId = 2,
                            FishType = "Pike",
                            MemberId = 9,
                            Place = 9,
                            Weight = 5.5m
                        },
                        new
                        {
                            Id = 20,
                            CompetitionId = 2,
                            FishType = "Carp",
                            MemberId = 10,
                            Place = 10,
                            Weight = 6.0m
                        },
                        new
                        {
                            Id = 21,
                            CompetitionId = 3,
                            FishType = "Pike",
                            MemberId = 1,
                            Place = 1,
                            Weight = 1.5m
                        },
                        new
                        {
                            Id = 22,
                            CompetitionId = 3,
                            FishType = "Carp",
                            MemberId = 2,
                            Place = 2,
                            Weight = 2.0m
                        },
                        new
                        {
                            Id = 23,
                            CompetitionId = 3,
                            FishType = "Pike",
                            MemberId = 3,
                            Place = 3,
                            Weight = 2.5m
                        },
                        new
                        {
                            Id = 24,
                            CompetitionId = 3,
                            FishType = "Carp",
                            MemberId = 4,
                            Place = 4,
                            Weight = 3.0m
                        },
                        new
                        {
                            Id = 25,
                            CompetitionId = 3,
                            FishType = "Pike",
                            MemberId = 5,
                            Place = 5,
                            Weight = 3.5m
                        },
                        new
                        {
                            Id = 26,
                            CompetitionId = 3,
                            FishType = "Carp",
                            MemberId = 6,
                            Place = 6,
                            Weight = 4.0m
                        },
                        new
                        {
                            Id = 27,
                            CompetitionId = 3,
                            FishType = "Pike",
                            MemberId = 7,
                            Place = 7,
                            Weight = 4.5m
                        },
                        new
                        {
                            Id = 28,
                            CompetitionId = 3,
                            FishType = "Carp",
                            MemberId = 8,
                            Place = 8,
                            Weight = 5.0m
                        },
                        new
                        {
                            Id = 29,
                            CompetitionId = 3,
                            FishType = "Pike",
                            MemberId = 9,
                            Place = 9,
                            Weight = 5.5m
                        },
                        new
                        {
                            Id = 30,
                            CompetitionId = 3,
                            FishType = "Carp",
                            MemberId = 10,
                            Place = 10,
                            Weight = 6.0m
                        },
                        new
                        {
                            Id = 31,
                            CompetitionId = 4,
                            FishType = "Pike",
                            MemberId = 1,
                            Place = 1,
                            Weight = 1.5m
                        },
                        new
                        {
                            Id = 32,
                            CompetitionId = 4,
                            FishType = "Carp",
                            MemberId = 2,
                            Place = 2,
                            Weight = 2.0m
                        },
                        new
                        {
                            Id = 33,
                            CompetitionId = 4,
                            FishType = "Pike",
                            MemberId = 3,
                            Place = 3,
                            Weight = 2.5m
                        },
                        new
                        {
                            Id = 34,
                            CompetitionId = 4,
                            FishType = "Carp",
                            MemberId = 4,
                            Place = 4,
                            Weight = 3.0m
                        },
                        new
                        {
                            Id = 35,
                            CompetitionId = 4,
                            FishType = "Pike",
                            MemberId = 5,
                            Place = 5,
                            Weight = 3.5m
                        },
                        new
                        {
                            Id = 36,
                            CompetitionId = 4,
                            FishType = "Carp",
                            MemberId = 6,
                            Place = 6,
                            Weight = 4.0m
                        },
                        new
                        {
                            Id = 37,
                            CompetitionId = 4,
                            FishType = "Pike",
                            MemberId = 7,
                            Place = 7,
                            Weight = 4.5m
                        },
                        new
                        {
                            Id = 38,
                            CompetitionId = 4,
                            FishType = "Carp",
                            MemberId = 8,
                            Place = 8,
                            Weight = 5.0m
                        },
                        new
                        {
                            Id = 39,
                            CompetitionId = 4,
                            FishType = "Pike",
                            MemberId = 9,
                            Place = 9,
                            Weight = 5.5m
                        },
                        new
                        {
                            Id = 40,
                            CompetitionId = 4,
                            FishType = "Carp",
                            MemberId = 10,
                            Place = 10,
                            Weight = 6.0m
                        },
                        new
                        {
                            Id = 41,
                            CompetitionId = 5,
                            FishType = "Pike",
                            MemberId = 1,
                            Place = 1,
                            Weight = 1.5m
                        },
                        new
                        {
                            Id = 42,
                            CompetitionId = 5,
                            FishType = "Carp",
                            MemberId = 2,
                            Place = 2,
                            Weight = 2.0m
                        },
                        new
                        {
                            Id = 43,
                            CompetitionId = 5,
                            FishType = "Pike",
                            MemberId = 3,
                            Place = 3,
                            Weight = 2.5m
                        },
                        new
                        {
                            Id = 44,
                            CompetitionId = 5,
                            FishType = "Carp",
                            MemberId = 4,
                            Place = 4,
                            Weight = 3.0m
                        },
                        new
                        {
                            Id = 45,
                            CompetitionId = 5,
                            FishType = "Pike",
                            MemberId = 5,
                            Place = 5,
                            Weight = 3.5m
                        },
                        new
                        {
                            Id = 46,
                            CompetitionId = 5,
                            FishType = "Carp",
                            MemberId = 6,
                            Place = 6,
                            Weight = 4.0m
                        },
                        new
                        {
                            Id = 47,
                            CompetitionId = 5,
                            FishType = "Pike",
                            MemberId = 7,
                            Place = 7,
                            Weight = 4.5m
                        },
                        new
                        {
                            Id = 48,
                            CompetitionId = 5,
                            FishType = "Carp",
                            MemberId = 8,
                            Place = 8,
                            Weight = 5.0m
                        },
                        new
                        {
                            Id = 49,
                            CompetitionId = 5,
                            FishType = "Pike",
                            MemberId = 9,
                            Place = 9,
                            Weight = 5.5m
                        },
                        new
                        {
                            Id = 50,
                            CompetitionId = 5,
                            FishType = "Carp",
                            MemberId = 10,
                            Place = 10,
                            Weight = 6.0m
                        });
                });

            modelBuilder.Entity("Haczykowefajtlapy.Model.FishingCompetition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompetitionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("FishingCompetitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompetitionType = "Club",
                            Date = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Lake Nord",
                            Name = "Spring Challenge"
                        },
                        new
                        {
                            Id = 2,
                            CompetitionType = "Open",
                            Date = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "River East",
                            Name = "Summer Derby"
                        },
                        new
                        {
                            Id = 3,
                            CompetitionType = "Club",
                            Date = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Bay West",
                            Name = "Autumn Cup"
                        },
                        new
                        {
                            Id = 4,
                            CompetitionType = "Open",
                            Date = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Lake South",
                            Name = "Winter Tournament"
                        },
                        new
                        {
                            Id = 5,
                            CompetitionType = "Club",
                            Date = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Lake Nord",
                            Name = "New Year Bash"
                        });
                });

            modelBuilder.Entity("Haczykowefajtlapy.Model.FishingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FishType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("FishingLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 1,
                            Weight = 0.75m
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 2,
                            Weight = 1.00m
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 3,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2023, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 4,
                            Weight = 1.50m
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 5,
                            Weight = 0.50m
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 6,
                            Weight = 0.75m
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2023, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 7,
                            Weight = 1.00m
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2023, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 8,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2023, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 9,
                            Weight = 1.50m
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 10,
                            Weight = 0.50m
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2023, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 11,
                            Weight = 0.75m
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 12,
                            Weight = 1.00m
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 13,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 14,
                            Weight = 1.50m
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 15,
                            Weight = 0.50m
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2023, 4, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 16,
                            Weight = 0.75m
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2023, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 17,
                            Weight = 1.00m
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 18,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2023, 7, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 19,
                            Weight = 1.50m
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 20,
                            Weight = 0.50m
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2023, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 1,
                            Weight = 0.75m
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 2,
                            Weight = 1.00m
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2023, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 3,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2023, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 4,
                            Weight = 1.50m
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 5,
                            Weight = 0.50m
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2023, 2, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 6,
                            Weight = 0.75m
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2023, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 7,
                            Weight = 1.00m
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2023, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 8,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 9,
                            Weight = 1.50m
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 10,
                            Weight = 0.50m
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2023, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 11,
                            Weight = 0.75m
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 12,
                            Weight = 1.00m
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 13,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 14,
                            Weight = 1.50m
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 15,
                            Weight = 0.50m
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 16,
                            Weight = 0.75m
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 17,
                            Weight = 1.00m
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 18,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2023, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 19,
                            Weight = 1.50m
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2023, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 20,
                            Weight = 0.50m
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2023, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 1,
                            Weight = 0.75m
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 2,
                            Weight = 1.00m
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 3,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2023, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 4,
                            Weight = 1.50m
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2023, 9, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 5,
                            Weight = 0.50m
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 6,
                            Weight = 0.75m
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2023, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 7,
                            Weight = 1.00m
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 8,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Bream",
                            Location = "Lake Nord",
                            MemberId = 9,
                            Weight = 1.50m
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2023, 2, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FishType = "Roach",
                            Location = "River East",
                            MemberId = 10,
                            Weight = 0.50m
                        });
                });

            modelBuilder.Entity("Haczykowefajtlapy.Model.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LicenseValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MembershipFeePaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member1@fishingclub.com",
                            FirstName = "Member1",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname1",
                            LicenseValidUntil = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = false,
                            Phone = "6001001001"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member2@fishingclub.com",
                            FirstName = "Member2",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname2",
                            LicenseValidUntil = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = true,
                            Phone = "6001001002"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2003, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member3@fishingclub.com",
                            FirstName = "Member3",
                            IsActive = false,
                            JoinDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname3",
                            LicenseValidUntil = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = false,
                            Phone = "6001001003"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member4@fishingclub.com",
                            FirstName = "Member4",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname4",
                            LicenseValidUntil = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = true,
                            Phone = "6001001004"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member5@fishingclub.com",
                            FirstName = "Member5",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname5",
                            LicenseValidUntil = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = false,
                            Phone = "6001001005"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2006, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member6@fishingclub.com",
                            FirstName = "Member6",
                            IsActive = false,
                            JoinDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname6",
                            LicenseValidUntil = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = true,
                            Phone = "6001001006"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2007, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member7@fishingclub.com",
                            FirstName = "Member7",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname7",
                            LicenseValidUntil = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = false,
                            Phone = "6001001007"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(2008, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member8@fishingclub.com",
                            FirstName = "Member8",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname8",
                            LicenseValidUntil = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = true,
                            Phone = "6001001008"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member9@fishingclub.com",
                            FirstName = "Member9",
                            IsActive = false,
                            JoinDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname9",
                            LicenseValidUntil = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = false,
                            Phone = "6001001009"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member10@fishingclub.com",
                            FirstName = "Member10",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname10",
                            LicenseValidUntil = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = true,
                            Phone = "6001001010"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member11@fishingclub.com",
                            FirstName = "Member11",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname11",
                            LicenseValidUntil = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = false,
                            Phone = "6001001011"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member12@fishingclub.com",
                            FirstName = "Member12",
                            IsActive = false,
                            JoinDate = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname12",
                            LicenseValidUntil = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = true,
                            Phone = "6001001012"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(2013, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member13@fishingclub.com",
                            FirstName = "Member13",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname13",
                            LicenseValidUntil = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = false,
                            Phone = "6001001013"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member14@fishingclub.com",
                            FirstName = "Member14",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname14",
                            LicenseValidUntil = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = true,
                            Phone = "6001001014"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member15@fishingclub.com",
                            FirstName = "Member15",
                            IsActive = false,
                            JoinDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname15",
                            LicenseValidUntil = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = false,
                            Phone = "6001001015"
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member16@fishingclub.com",
                            FirstName = "Member16",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname16",
                            LicenseValidUntil = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = true,
                            Phone = "6001001016"
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member17@fishingclub.com",
                            FirstName = "Member17",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname17",
                            LicenseValidUntil = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = false,
                            Phone = "6001001017"
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member18@fishingclub.com",
                            FirstName = "Member18",
                            IsActive = false,
                            JoinDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname18",
                            LicenseValidUntil = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = true,
                            Phone = "6001001018"
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member19@fishingclub.com",
                            FirstName = "Member19",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname19",
                            LicenseValidUntil = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = false,
                            Phone = "6001001019"
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member20@fishingclub.com",
                            FirstName = "Member20",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Surname20",
                            LicenseValidUntil = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipFeePaid = true,
                            Phone = "6001001020"
                        });
                });

            modelBuilder.Entity("Haczykowefajtlapy.Model.CompetitionResult", b =>
                {
                    b.HasOne("Haczykowefajtlapy.Model.FishingCompetition", "Competition")
                        .WithMany("Results")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Haczykowefajtlapy.Model.Member", "Member")
                        .WithMany("CompetitionResults")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Haczykowefajtlapy.Model.FishingLog", b =>
                {
                    b.HasOne("Haczykowefajtlapy.Model.Member", "Member")
                        .WithMany("FishingLogs")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Haczykowefajtlapy.Model.FishingCompetition", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Haczykowefajtlapy.Model.Member", b =>
                {
                    b.Navigation("CompetitionResults");

                    b.Navigation("FishingLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
